# H2 DataBase?
spring:
  application:
    name: spring-batch
  datasource:
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:mem:batch
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # H2 Console
      path: /h2-console  # H2 Console Path
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 8010