# H2 DataBase?
spring:
  profiles:
    active: local
  application:
    name: spring-batch
  datasource:
    hikari:
      maximum-pool-size: 10
  batch:
    job:
      enabled: false
  sql:
    init:
      mode: never
  config:
    import: classpath:secret.yml
server:
  port: 8010
management:
  endpoints:
    web:
      exposure:
        include: '*'

