# H2 DataBase?
spring:
  profiles:
    active: local
  application:
    name: spring-batch
  datasource:
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
  batch:
    job:
      enabled: false
  sql:
    init:
      mode: never
  config:
    import: classpath:secret.yml
server:
  port: 8010

